<a href="https://colab.research.google.com/github/alevmore/datascience_hw/blob/main/modul_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Заміна непарних чисел на -1
arr[arr % 2 != 0] = -1

print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [23]:
# 2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками
arr_1d = np.arange (1,16, 2)
arr_2d= arr_1d.reshape(2,4)
print (arr_1d)
print (arr_2d)


[ 1  3  5  7  9 11 13 15]
[[ 1  3  5  7]
 [ 9 11 13 15]]


In [38]:
# 3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально
a = np.random.randint (1, 16, size=(2,3))
b = np.random.randint (1, 35, size=(3,6))
print (a)
print (a.T)
print (b)
print (b.T)

[[ 8  8  5]
 [15 13 11]]
[[ 8 15]
 [ 8 13]
 [ 5 11]]
[[33  2 26  9 12 17]
 [34 18  7  2 34 23]
 [14 21 27 23 13  4]]
[[33 34 14]
 [ 2 18 21]
 [26  7 27]
 [ 9  2 23]
 [12 34 13]
 [17 23  4]]


In [51]:
# 4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])
# Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])
aa = np.repeat(a,3)
ab = np.tile (a,3)
aa_ab = np.concatenate((aa, ab))
print(aa_ab)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [52]:
# 5. Отримайте спільні елементи між a і b a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a_b = np.intersect1d(a, b)
print (a_b)

[2 4]


In [58]:
# 6. Отримайте позиції перших 5 максимальних значень у заданому масиві a np.random.seed(100) a = np.random.uniform(1,50, 20)

a = np.random.seed(100)
a = np.random.uniform(1,50, 20)
a_max = np.sort(a.flatten())[-5:]
print (a)
print (a_max)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


In [80]:
# 7. Вилучіть усі значення NaN із одновимірного  а=np.array([1,2,3,np.nan,5,6,7,np.nan])
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])

# Вилучення значень NaN
a_without_nan = a[~np.isnan(a)]

print(a_without_nan)

[1. 2. 3. 5. 6. 7.]


In [106]:
# 8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
distance = np.linalg.norm(a - b)
print (distance)

6.708203932499369


In [86]:
# 9. Знайдіть індекс 5-го повторення числа 1 у масиві x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
index = np.argwhere(x == 1)[5]
print (index)


[10]


In [105]:
# 10 np.random.seed(100) a = np.random.randint(0, 5, 10) [0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

import numpy as np

np.random.seed(100)
a = np.random.randint(0, 5, 10)

# Створюємо масив, в якому перше входження кожного елемента відмічене як False
first_occurrence = np.ones_like(a, dtype=bool)
first_occurrence[np.unique(a, return_index=True)[1]] = False

# Визначаємо повторені записи
repeated_entries = ~first_occurrence
print (a)
print(repeated_entries)


[0 0 3 0 2 4 2 2 2 2]
[ True False  True False  True  True False False False False]
