<a href="https://colab.research.google.com/github/alevmore/datascience_hw/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
import numpy as np
a = np.array([1, 2, 3, 4, 5, 7, 8, 6, 9, 10], dtype=int)
b= np.arange (1,11)
print(a)
print (b)

[ 1  2  3  4  5  7  8  6  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення
b = np.zeros((3, 3), dtype="u4")
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
arr = np.random.randint(1, 11, size=(5,5))
print (arr)

[[ 5  6  8  7  2]
 [ 3  1  3 10  5]
 [ 4  7  1  5  2]
 [ 8 10 10  7  9]
 [10  2  2  7  2]]


In [4]:
# 4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення
import numpy as np
arr = np.random.random((4,4))
print (arr)

[[0.30634274 0.93521224 0.73852379 0.64002798]
 [0.79065529 0.03415297 0.20699756 0.06757206]
 [0.25037879 0.04969519 0.49252559 0.61834539]
 [0.30179781 0.71980988 0.68918464 0.1682561 ]]


In [ ]:
# 5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(1, 11, size=(5,))
b= np.random.randint(1, 11, size=(5,))

print (a, b, a+b, a-b, a*b)

[5 4 4 3 3] [10 10  6  6  5] [15 14 10  9  8] [-5 -6 -2 -3 -2] [50 40 24 18 15]


In [ ]:
# 6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a = np.arange(7)
b= np.arange (2,9)
print (np.dot(a, b))

133


In [ ]:
# 7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
arr1 = np.random.randint(1, 11, size=(2,2))
arr2 = np.random.randint(1, 11, size=(2,3))
print (np.dot(arr1,arr2))

[[ 55  65  13]
 [ 86 100  20]]


In [ ]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
a = np.random.randint(1, 11, size=(3,3))
print(a)
print(np.linalg.inv(a))

[[ 2  7 10]
 [ 4  3  3]
 [ 9 10 10]]
[[ 0.          0.76923077 -0.23076923]
 [-0.33333333 -1.79487179  0.87179487]
 [ 0.33333333  1.1025641  -0.56410256]]


In [ ]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a = np.random.random((4,4))
print (a)
print(a.T)

[[0.89062034 0.39683395 0.9178588  0.61529694]
 [0.34737388 0.36932949 0.57915069 0.52189544]
 [0.76552046 0.73653299 0.05218339 0.60439872]
 [0.93332957 0.88045744 0.92173607 0.65099021]]
[[0.89062034 0.34737388 0.76552046 0.93332957]
 [0.39683395 0.36932949 0.73653299 0.88045744]
 [0.9178588  0.57915069 0.05218339 0.92173607]
 [0.61529694 0.52189544 0.60439872 0.65099021]]


In [13]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
a = np.random.randint(1, 11, size=(3,4))
b= np.arange (1,11, 4)
print (np.dot (b,a))

[58 97 98 32]


In [10]:
# 11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a = np.random.random((2,3))
b= np.random.random(3,)
print (a,b)
print (np.dot(a,b))


[[0.11614007 0.69084191 0.88189062]
 [0.47924344 0.7694318  0.72520299]] [0.35156178 0.02185003 0.61136083]
[0.59507871 0.62865649]


In [6]:
# 12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a= np.random.randint(1, 11, size=(2,2))
b= np.random.randint(1, 11, size=(2,2))
print (a*b)

[[80  7]
 [ 9  9]]


In [7]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a= np.random.randint(1, 11, size=(2,2))
b= np.random.randint(1, 11, size=(2,2))
print (np.dot(a,b))

[[21 19]
 [60 44]]


In [ ]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a= np.random.randint(1, 101, size=(5,5))
print (a.sum())

1322


In [ ]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a= np.random.randint(1, 11, size=(4,4))
b= np.random.randint(1, 11, size=(4,4))
print (a-b)

[[ 1  1 -7  1]
 [-4 -4  8  4]
 [ 1 -1  2  6]
 [-6  2 -5 -2]]


In [26]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
a= np.random.random((3,3))
b= np.sum (a, axis=1, keepdims=True)
c = np.sum (a, axis=1)
print (a)
print (b)


[[0.2681647  0.73254678 0.19527843]
 [0.35019275 0.03115592 0.59634782]
 [0.08172045 0.30055312 0.91726806]]
[[1.19598991]
 [0.97769649]
 [1.29954162]]


In [5]:
# 17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a= np.random.randint(12, size=(3,4))
a_sq= np.square(a)
print (a)
print (a_sq)

[[ 0 10  8  0]
 [ 1  2  3 10]
 [ 8  0 10  3]]
[[  0 100  64   0]
 [  1   4   9 100]
 [ 64   0 100   9]]


In [ ]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
a= np.random.randint(1, 51, size=(4,))
a_sqrt = np.sqrt (a)
print (a)
print (a_sqrt)

[28 20 18 27]
[5.29150262 4.47213595 4.24264069 5.19615242]
